var todoConstants = {
  TODO_CREATE: 'TODO_CREATE',
  TODO_COMPLETE: 'TODO_COMPLETE',
  TODO_DESTROY: 'TODO_DESTROY',
  TODO_DESTROY_COMPLETED: 'TODO_DESTROY_COMPLETED',
  TODO_TOGGLE_COMPLETE_ALL: 'TODO_TOGGLE_COMPLETE_ALL',
  TODO_TOGGLE_COMPLETE: 'TODO_TOGGLE_COMPLETE'
};

module.exports = todoConstants;
